# -*- coding: utf-8 -*-
"""Web scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8wpSw4bg8j7gnaK1KbcssB2FOMpyeSJ
"""

#web scrapping
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue'

page = requests.get(url)
page

soup = BeautifulSoup(page.text,'lxml')

soup

table = soup.find('table', {'class': 'wikitable'})

table

headers = [th.get_text(strip=True) for th in table.find('tr').find_all('th')]

print(headers)

rows = []
for tr in table.find_all('tr')[1:]:  # Skip header row
    cells = tr.find_all(['th', 'td']) # Include both th and td to handle rows with missing <td>
    row = [cell.get_text(strip=True) for cell in cells]
    rows.append(row)

print(rows)

# Create DataFrame
df = pd.DataFrame(rows, columns=headers)

df

# Save to CSV
csv_file = "largest_companies.csv"
df.to_csv(csv_file, index=False)

from google.colab import files
files.download(csv_file)